#!/bin/bash
#
# Run all 22 TPC-H queries sequentially against a TPCH database/schema.
# Default schema is tpch_sf1000 = 1TB.
#
# Assumes Snowflake account, username/password, warehouse are separately
# specified in snowsql configuration file: ~/.snowsql/config

now=`date +%Y%m%d-%H%M%S`
db=${1:-TPC}
schema=${2:-TPCH_SF1000}
outfile=$schema\_${db:0:6}\_$now.out

exec >$outfile
exec 2>&1

# disable cached results to ensure query is executed for proper timing,
snowsql -d $db -o friendly=False -o echo=True << eof
	alter user set use_cached_result=False;
eof

echo "DB: $db"
echo "TPCH Schema: $schema"
echo
sync

# Do 2 runs to warm up the SSD caches to eliminate remote IO
#
for i in {1..22}
do
  for count in {1..3}
  do
     ./run_tpch_query q$i.sql $db $schema $outfile
  done
done
sync

snowsql -o friendly=False -o echo=True << eof
        !queries amount=10 duration=60000;
eof
