#!/bin/bash 
# 
# Run TPC-H query on different scaling-factor (SF) schemas 
# Default DB is SAMPLE_DATA share provided by Snowflake. 
# Default schema is TPCH_SF1000 = 1TB raw dataset.
#
# Assumes Snowflake account, username, password, warehouse
# have all been separately specified in SnowSQL config file
# at ~/.snowsql/config
# 
if [ "$#" -eq 0 ]; then     
	echo "Usage: $0 <queryfile> <database> [schema] [outfile]"
        exit 1
fi

qfile=$1
db=${2:-SAMPLE_DATA}
schema=${3:-TPCH_SF1000}
outfile=${4:-${db:0:5}\_$schema\_${qfile:0:2}.out}

exec >>$outfile
exec 2>&1

echo "== TPC-H Query${qfile:1:2} =="
snowsql -d $db -s $schema -f $qfile -o friendly=False -o timing=True \
-o execution_only=True -o output_format=csv -o header=False

sync
